version: "3.8"

services:
  pgdb:
    image: postgres:latest
    container_name: pgdb
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    expose:
      - 6379

  app:
    build: .
    container_name: app
    command: ./entrypoint.sh
    env_file:
      - .env
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - pgdb
      - redis

  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  postgres_data:
  static_volume:
  media_volume: