version: "3.8"
services:
  pgdb:
    image: postgres:latest
    container_name: pgdb
    env_file:
      - .env
    volumes:
      - ./postgres/init.sql:/dockerr-entrypoint-initdb.d/init.sql
      - pgdbdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    expose:
      - 6379

  app:
    build: .
    container_name: app
    command: sh -c "sleep 5 && ./dev/docker-entrypoint.sh"
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - pgdb
      - redis

volumes:
  pgdbdata: null