# Generated by Django 5.0.2 on 2024-03-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
