# Generated by Django 5.0.2 on 2024-02-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
