# Generated by Django 5.0.2 on 2024-02-28 07:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('shopapp', '0003_alter_product_content'), ('shopapp', '0004_alter_category_options_alter_product_options_and_more'), ('shopapp', '0005_alter_product_amount_alter_product_image')]

    dependencies = [
        ('shopapp', '0002_alter_category_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created_at',), 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Цена за покупку'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shopapp/', verbose_name='Изображение'),
        ),
    ]
