name: main

on:
  push:
    branches:
      - 'main'

env:
  TEST_TAG: repo/shop-project-app:test

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}

      - run: export $(grep -v '^#' .env | xargs)

      - run: make tests

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: nk3qq/shop_project_app:latest
