name: main

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v2
        with:
          docker-version: '20.10.7'

      - name: Create .env file
        run: echo "ENV_STAGE=${{ secrets.ENV_STAGE }}" > .env
          
      - name: Build and run docker-compose
        run: make docker-compose-run
        
      - name: Run tests
        run: make tests

      - name: Clean up
        run: make clean-up
